language: python
python:
- 2.7
- 3.6
- 3.7
matrix:
  allow_failures:
    - python: 3.7

sudo: false

env:
  global:
    - MASTER_BRANCH=master
    - PYPI_PY=3.6  # deploy to pypi from python 3.6

# Setup anaconda
before_install:
# Install packages
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes pytest pytest-cov sphinx_rtd_theme sphinx
  - python setup.py install

script:
  - make test
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then
      conda install black flake8 pylint;
      make check;
      make lint;
    fi

after_success:

  - bash <(curl -s https://codecov.io/bash)

  # early exit if not on a deplotment branch
  - if ! [ "$TRAVIS_BRANCH" = "$MASTER_BRANCH" -o "$TRAVIS_TAG" = "true" ]; then
      echo "Not deploying (because this is not a deployment branch)" ;
      exit 0 ;
    fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
      echo "Not deploying (because this is a pull request)" ;
      exit 0 ;
    fi

  # unpack credentials
  - openssl aes-256-cbc -K $encrypted_9f42beb9a57a_key -iv $encrypted_9f42beb9a57a_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz

  # deploy to pypi on tags
  - mv credentials/.pypirc ~/.pypirc ;
  - make deploy;


notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
