language: python
python:
- 2.7
- 3.5
- 3.6
- "nightly"
matrix:
  allow_failures:
    - python: "nightly"

sudo: false

env:
  global:
    - MASTER_BRANCH=master
    - PYPI_PY=3.6  # deploy to pypi from python 3.6
    - TEST_DIR=tests

install:
  - pip install --upgrade pip
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - cd $TEST_DIR; pytest . --cov=$TRAVIS_HOME --cov-config ../.coveragerc -v -s; cd ../
  - if [ ${TRAVIS_PYTHON_VERSION} >= "3.6" ]; then
      pip install black flake8 pylint;
      make check;
      make lint;
    fi

after_success:
  - if [ "$TEST" == "true" ]; then
      coverage xml;
      echo "Uploading coverage to Codecov";
      codecov -e $TRAVIS_PYTHON_VERSION ;
    fi

deploy:
  - provider: script
    script: ci/deploy-pypi.sh
    on:
        tags: true
        branch: master

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
